### ISSUE TITLE
Python errror: 'portName' is not defined

### ISSUE THREAD

**Issue by AudD-music** [ojacques/SynthesiaKontrol#1]
```
C:\SynthesiaKontrol>SynthesiaKontrol
Connecting to Komplete Kontrol Keyboard
Opening LoopBe input port
Listening to Midi
Traceback (most recent call last):
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "SynthesiaKontrol.py", line 106, in <module>
NameError: name 'portName' is not defined
```
When I open SynthesiaKontrol.exe from file explorer, it just closing.

**Comment by ojacques** [comment]
Thanks for the report @AudD-music. 
I will handle better that error, but can it be that you have not installed LoopBe1 virtual midi port driver as per the [README](https://github.com/ojacques/SynthesiaKontrol/blob/master/README.md) ?
