### ISSUE TITLE
OSError: open failed

### ISSUE THREAD

**Issue by WasKa001** [ojacques/SynthesiaKontrol#2]
I'm getting this errors when running SynthesiaKontrol under Windows 10 (Loop be installed and configured in Synthesia 10.4)

D:\SynthesiaKontrol>SynthesiaKontrol.exe
Connecting to Komplete Kontrol Keyboard
Traceback (most recent call last):
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "SynthesiaKontrol.py", line 98, in <module>
  File "SynthesiaKontrol.py", line 19, in init
  File "hid.pyx", line 66, in hid.device.open
OSError: open failed

D:\SynthesiaKontrol>

**Comment by norbertmocsnik** [comment]
Same on macOS (after commenting out seemingly unnecessary msvcrt which doesn't exist on macOS):

$ python SynthesiaKontrol.py
Connecting to Komplete Kontrol Keyboard
Traceback (most recent call last):
File "SynthesiaKontrol.py", line 100, in 
connected = init()
File "SynthesiaKontrol.py", line 21, in init
device.open(0x17cc, 0x1620)
File "hid.pyx", line 66, in hid.device.open
IOError: open failed

**Comment by ojacques** [comment]
@norbertmocsnik - sorry for the very long delay. 
May I ask you which Komplete Kontrol Device are you trying to use?

**Comment by ojacques** [comment]
@norbertmocsnik I just added support for MK1. I have not been able to test it though. Can you try it out and report?
Thanks!
https://github.com/ojacques/SynthesiaKontrol/releases

**Comment by ojacques** [comment]
According to reports to #5, MK1 is now supported and working. Going ahead and closing.
Thank you so much for the report!

**Comment by WasKa001** [comment]
Hi @ojacques 

I tried it with Komplete Kontrol S49 and it doesn't work. THe only available options are 61 and 88 keys. Does it support 49 key model MK1 please? Error is as below"

"D:\SynthesiaKontrol.v1.1>SynthesiaKontrol.exe
Select your keyboard (*1,2,3,4):
  1-Komplete Kontrol S61 MK2
  2-Komplete Kontrol S88 MK2
  3-Komplete Kontrol S61 MK1
  4-Komplete Kontrol S88 MK1
3
Connecting to Komplete Kontrol Keyboard
Opening Keyboard device...
Traceback (most recent call last):
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "SynthesiaKontrol.py", line 200, in <module>
  File "SynthesiaKontrol.py", line 24, in init
  File "hid.pyx", line 66, in hid.device.open
OSError: open failed"

I am not sure why it's looking for file in C;\Users\jacqu\****  - this looks like a path to your local hard drive
