### ISSUE TITLE
Exe file not working on Windows, seems that the paths to dependencies are hardcoded

### ISSUE THREAD

**Issue by CEAC33** [ojacques/SynthesiaKontrol#29]
C:\Users\Hackintosh X99\Documents\SynthesiaKontrol.v1.1\SynthesiaKontrol.v1.1>SynthesiaKontrol.exe
Select your keyboard (*1,2,3,4):
  1-Komplete Kontrol S61 MK2
  2-Komplete Kontrol S88 MK2
  3-Komplete Kontrol S61 MK1
  4-Komplete Kontrol S88 MK1
3
Connecting to Komplete Kontrol Keyboard
Opening Keyboard device...
Turn off lights for all notes
Connected to Komplete Kontrol!
Turn off lights for all notes
Opening LoopBe input port
Traceback (most recent call last):
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "SynthesiaKontrol.py", line 206, in <module>
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mido\backends\backend.py", line 169, in get_input_names
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mido\backends\backend.py", line 162, in _get_devices
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mido\backends\backend.py", line 42, in module
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mido\backends\backend.py", line 58, in load
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\mido\backends\rtmidi.py", line 8, in <module>
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\rtmidi\__init__.py", line 4, in <module>
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

**Comment by ojacques** [comment]
@CEAC33, the paths you see are because of the packaging of the application. It seems you use 1.1. Could I ask you to try [one of the latest release](https://github.com/ojacques/SynthesiaKontrol/releases)?

**Comment by CEAC33** [comment]
Using the last version I'm getting this error
```
PS C:\Users\Hackintosh X99\Documents\SynthesiaKontrol.v1.3\SynthesiaKontrol.v1.3> .\SynthesiaKontrol.exe
Select your keyboard (1,2,3,...):
  1-Komplete Kontrol S61 MK2
  2-Komplete Kontrol S88 MK2
  3-Komplete Kontrol S49 MK2
  4-Komplete Kontrol S61 MK1
  5-Komplete Kontrol S88 MK1
  6-Komplete Kontrol S49 MK1
  7-Komplete Kontrol S25 MK1
1
Connecting to Komplete Kontrol Keyboard
Opening Keyboard device...
Error: open failed
Traceback (most recent call last):
  File "SynthesiaKontrol.py", line 26, in init
  File "hid.pyx", line 66, in hid.device.open
OSError: open failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python38\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "SynthesiaKontrol.py", line 224, in <module>
  File "SynthesiaKontrol.py", line 29, in init
NameError: name 'quit' is not defined
```

**Comment by ojacques** [comment]
Interesting:
```
Opening Keyboard device...
Error: open failed
Traceback (most recent call last):
  File "SynthesiaKontrol.py", line 26, in init
  File "hid.pyx", line 66, in hid.device.open
OSError: open failed
```

Few questions for you:
- You seem to have an S61 MK2 (like mine), do you confirm?
- Do you have Komplete Kontrol opened? If yes, close it and try again.
- Just making sure: your KK keyboard is plugged in (USB) to your computer, and when you open Komplete Kontrol, it works normally, right?
- Are you on Windows, or going some sort of a mix between Mac/Windows VM?

**Comment by ojacques** [comment]
Thanks for the report @CEAC33! This was a packaging issue with the old v1.1 build where rtmidi DLLs weren't bundled correctly by cx_Freeze.

We've just released **v1.5** which is built with Python 3.12 and a modern cx_Freeze pipeline via GitHub Actions — DLL bundling is now handled properly.

Please download v1.5 from the [releases page](https://github.com/ojacques/SynthesiaKontrol/releases/tag/v1.5). Closing as fixed — feel free to reopen if the issue persists with the new version.
