### ISSUE TITLE
LoopBe detection fails (Windows 11)

### ISSUE THREAD

**Issue by kobolttti** [ojacques/SynthesiaKontrol#36]
Running SynthesiaKontrol.v1.4 + LoopBe1 v1.6 + Windows 11.

LoopBe detection fails:

```
Connecting to Komplete Kontrol Keyboard
Opening Keyboard device...
Turn off lights for all notes
Connected to Komplete Kontrol!
Turn off lights for all notes
Opening LoopBe input port
Error: can't find 'LoopBe' midi port. Please install LoopBe1 from http://www.nerds.de/en/download.html (Windows) or name your IAC midi device 'LoopBe' (on Mac).
Traceback (most recent call last):
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 130, in run
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "SynthesiaKontrol.py", line 245, in <module>
NameError: name 'exit' is not defined
```

Does not seem to find any ports as there is no "Found MIDI port" outputs. LoopBe1 is visible in both Device Manager and Synthesia settings. "Run as administrator" does not help either.

What to check? Should SynthesiaKontrol work on Windows 11?

Additionally, "exit(1)" in "SynthesiaKontrol.py", line 245 fails with the traceback seen above.

**Comment by yabix007** [comment]
I got the same problem it doesnt recognize it.

The older Version works SynthesiaKontrol 1.3

**Comment by ojacques** [comment]
This is now fixed in **v1.5** 🎉

The root cause was that `quit()` and `exit()` are interactive helpers from Python's `site` module, which are not available in cx_Freeze frozen executables. This caused the `NameError` crashes.

All occurrences have been replaced with `sys.exit()`, and the build is now done with Python 3.12 + cx_Freeze 8.6.4.

Download the new release here: https://github.com/ojacques/SynthesiaKontrol/releases/tag/v1.5
