### ISSUE TITLE
NameError: name 'quit' is not defined

### ISSUE THREAD

**Issue by gigikentlight** [ojacques/SynthesiaKontrol#38]
Trying to get this running, and getting:

C:\Users\temp\Downloads\SynthesiaKontrol.v1.4>python3 --version
Python 3.12.4

C:\Users\temp\Downloads\SynthesiaKontrol.v1.4>SynthesiaKontrol.exe
Select your keyboard (1, 2, 3, ...) and press 'Enter':
  1-Komplete Kontrol S61 MK2
  2-Komplete Kontrol S88 MK2
  3-Komplete Kontrol S49 MK2
  4-Komplete Kontrol S61 MK1
  5-Komplete Kontrol S88 MK1
  6-Komplete Kontrol S49 MK1
  7-Komplete Kontrol S25 MK1
2
Connecting to Komplete Kontrol Keyboard
Opening Keyboard device...
Error: open failed
Traceback (most recent call last):
  File "SynthesiaKontrol.py", line 26, in init
  File "hid.pyx", line 142, in hid.device.open
OSError: open failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 130, in run
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "SynthesiaKontrol.py", line 232, in <module>
  File "SynthesiaKontrol.py", line 29, in init
NameError: name 'quit' is not defined

C:\Users\temp\Downloads\SynthesiaKontrol.v1.4>

looks like it's referencing files under jacqu username?

**Comment by ojacques** [comment]
This is now fixed in **v1.5** 🎉

The `NameError: name 'quit' is not defined` was caused by `quit()` and `exit()` being interactive helpers from Python's `site` module — they are not available in cx_Freeze frozen executables.

All occurrences have been replaced with `sys.exit()`, and the build is now done with Python 3.12 + cx_Freeze 8.6.4.

Download the new release here: https://github.com/ojacques/SynthesiaKontrol/releases/tag/v1.5
