### ISSUE TITLE
SynthesiaKontrol.exe closes after connecting

### ISSUE THREAD

**Issue by JGastager** [ojacques/SynthesiaKontrol#39]
I want to setup my KK88 Mk2 and did all the necessary steps showen by the instruction, but i cant get it to work.
I installed the LoopBe1 Midi Port and did set it up accordingly in Syntesia.
Can it be that the issue is that the SynthesiaKontrol.exe just closes after connecting to my Keyboard?
The keyboard does the Lightshow on connect and the Terminal says "Connected to KompleteKontrol!" but closes instantly after.
Is this normal?
I'm on Windows 10 and did run the .exe as admin.

Thx for any help.

**Comment by JGastager** [comment]
I now tried release v1.3 and it works fine. No crashing. Seams so be an issue with the new version 1.4.

**Comment by chucklesas1** [comment]
I've run into the same problem where 1.4 shuts down, but 1.3 does work (mostly). I've installed LoopBe1, so not sure why I'm getting this error. My internal midi is named LoopBe1, but the problem seems to be looking for LoopBe:

"Select your keyboard (1, 2, 3, ...) and press 'Enter':
  1-Komplete Kontrol S61 MK2
  2-Komplete Kontrol S88 MK2
  3-Komplete Kontrol S49 MK2
  4-Komplete Kontrol S61 MK1
  5-Komplete Kontrol S88 MK1
  6-Komplete Kontrol S49 MK1
  7-Komplete Kontrol S25 MK1
4
Connecting to Komplete Kontrol Keyboard
Opening Keyboard device...
Turn off lights for all notes
Connected to Komplete Kontrol!
Turn off lights for all notes
Opening LoopBe input port
Error: can't find 'LoopBe' midi port. Please install LoopBe1 from http://www.nerds.de/en/download.html (Windows) or name your IAC midi device 'LoopBe' (on Mac).
Traceback (most recent call last):
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 130, in run
  File "C:\Users\jacqu\AppData\Local\Programs\Python\Python310\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "SynthesiaKontrol.py", line 245, in <module>
NameError: name 'exit' is not defined"

**Comment by ojacques** [comment]
Thanks for reporting this @JGastager! This is now fixed in **v1.5** 🎉

The root cause was that the frozen .exe used `quit()` which isn't available in packaged executables (causes an instant crash/close). We've replaced all occurrences with `sys.exit()`.

Please download v1.5 from the [releases page](https://github.com/ojacques/SynthesiaKontrol/releases/tag/v1.5) and let us know if that resolves your issue. If the exe still closes, please run from source (`python SynthesiaKontrol.py`) so we can see the actual error message.

Closing as fixed in v1.5 — feel free to reopen if the issue persists.
